### ISSUE TITLE
CSS for HTML tables result in tables that are difficult to read

### ISSUE THREAD

**Issue by paul-grassi** [usnistgov/pages-root#2]
Can there be an option for column dividers?  This is how tables are rendered from markdown tables.

<img width="947" alt="screen shot 2016-08-22 at 11 08 47 am" src="https://cloud.githubusercontent.com/assets/13986911/17859763/ef62849e-6858-11e6-9972-402593d2f368.png">

**Comment by mdsteveb** [comment]
I just used the templates from @crhume for nist-pages sites.  (I forget which repo that is but it's in the FAQ page.)  I'm no CSS expert and I didn't write these, so I'd suggest talking to him, getting the changes made in that repo and then we can port them over here.

**Comment by mdsteveb** [comment]
It was the Pages-Template repo that the CSS here is copied from.

**Comment by mdsteveb** [comment]
Closing this issue due to age and no response.
